services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devscenarios-app
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - REDIS_URL=redis://redis:6379
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: devscenarios-redis
    ports:
      - "6380:6379"
    restart: always
